image: m1kev4ndyke/docker-gtest

stages:
    - install
    
install:
    stage: install
    script:
        - mkdir build
        - cd build
        - cmake ../
        - make install
    tags:
        - twexor-runner
