image: m1kev4ndyke/docker-gtest

stages:
    - build
    
build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ../
        - make
    tags:
        - twexor-runner

