image: m1kev4ndyke/docker-gtest

stages:
    - cmake
    - build
    
cmake:
    stage: cmake
    script:
        - mkdir build
        - cd build
        - cmake ../

build:
    stage: build
    script: make