image: gcc

stages:
    - before_script
    - cmake
    - build
    
install_cmake:
    stage: before_script
    script: sudo apt-get install cmake
    
cmake:
    stage: cmake
    script:
        - mkdir build
        - cd build
        - cmake ..

build:
    stage: build
    script: make